### PR TITLE
Add Cargo/Miri Test Pipeline

### PR DESCRIPTION
**Pull request by tomlegodais**
The following PR adds a simple pipeline using GitHub Actions to build and test rclite using both Cargo and Miri. The current configuration runs testing on push and pull request to the main branch.

### CODE REVIEW

**Comment by fereidani** [comment]
Hi thank you for your contribution,
Could you please remove the changes to the `.gitignore` as I think it's better for idea developers to use a global `.gitignore` for this purpose?
It would be better if you have these 4 tasks in your pipeline:
1. normal test run
2. normal test run with `--release`
3. Miri test
4. Miri test with `RUSTFLAGS="-Z randomize-layout"`

Also please edit your PR as a one commit for adding the GitHub actions.

**Comment by tomlegodais** [comment]
> Hi thank you for your contribution, Could you please remove the changes to the `.gitignore` as I think it's better for idea developers to use a global `.gitignore` for this purpose? It would be better if you have these 4 tasks in your pipeline:
> 
> 1. normal test run
> 2. normal test run with `--release`
> 3. Miri test
> 4. Miri test with `RUSTFLAGS="-Z randomize-layout"`
> 
> Also please edit your PR as a one commit for adding the GitHub actions.

I went ahead and added cargo test with release mode and miri test with the rustflags. As for your comment about the idea directory, there are certain aspects of that folder that you do not want to commit; so I went ahead and updated the gitignore accordingly. 

As for your last comment about editing the PR to be a single commit I'm unsure of how to do that; on your end couldn't you squash and merge?

**Comment by CosmicHorrorDev** [comment]
I'm assuming that @fereidani and I have the same philosophy for `.gitignore` files. They aren't asking you to commit the `.idea` directory. They're asking you to add it to a global `.gitignore` file. You can set this up by adding this to your `~/.gitconfig`

```ini
[core]
	excludesfile = ~/wherever/you/want/global_gitignore
```

and then `~/wherever/you/want/global_gitignore` just acts as a regular `.gitignore` that automatically applies to all of your projects

```text
.idea
```

If you do this then you no longer have to add `.idea` to the `.gitignore` of every project you work on. If everyone follows this then `.gitignore`s can just be relevant to things specific to that project instead of becoming an amalgamation of files that are generated by all the contributors' different workflows

**Comment by tomlegodais** [comment]
> I'm assuming that @fereidani and I have the same philosophy for `.gitignore` files. They aren't asking you to commit the `.idea` directory. They're asking you to add it to a global `.gitignore` file. You can set this up by adding this to your `~/.gitconfig`
> 
> ```ini
> [core]
> 	excludesfile = ~/wherever/you/want/global_gitignore
> ```
> 
> and then `~/wherever/you/want/global_gitignore` just acts as a regular `.gitignore` that automatically applies to all of your projects
> 
> ```
> .idea
> ```
> 
> If you do this then you no longer have to add `.idea` to the `.gitignore` of every project you work on. If everyone follows this then `.gitignore`s can just be relevant to things specific to that project instead of becoming an amalgamation of files that are generated by all the contributors' different workflows

Oooo this is interesting, I was unaware of this feature although I should have known it existed, that's awesome. Thank you 👍🏼

**Comment by fereidani** [comment]
@CosmicHorrorDev Thank you for your comment.
@tomlegodais Please take a look at https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History , please remove all these commit messages and transform them into one commit for `pipeline.yaml` , thank you.

**Comment by tomlegodais** [comment]
> @CosmicHorrorDev Thank you for your comment. @tomlegodais Please take a look at https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History , please remove all these commit messages and transform them into one commit for `pipeline.yaml` , thank you.

Will do. I also went ahead and moved the ignoring of the _.idea/_ directory to a global _.gitignore_ file. I also want to apologize for the spam of commits, something ended up breaking with my commit history and my IDE was bugging out so I had to fix it. Now I can go ahead and transform them into one commit.

**Comment by fereidani** [comment]
No problem at all, Let me know when your PR is ready!

**Pull request closed without merging**
